CatalogManager/ViewModels/CatalogViewModel.cs
using BusinessLogic.DTO;
using BusinessLogic.ParametrObjects.Requests.Catalogs;
using BusinessLogic.Services.Requests;
using FluentValidation;
using Microsoft.Extensions.Localization;

namespace CatalogsManager.ViewModels
{
    public class CatalogViewModel
    {
        public int CatalogId { get; set; }
        public string Kind { get; set; }
    }

    public class CatalogViewModelValidator : AbstractValidator<CatalogViewModel>
    {
        public CatalogViewModelValidator(IStringLocalizer<CatalogViewModel> localizer, 
            IRequestHandler<GetCatalogByKindRequest, CatalogDTO> service)
        {
            RuleFor(catalog => catalog.Kind)
               .NotEmpty()
               .WithName(localizer["CatalogType"])
               .MinimumLength(3)
               .Must((catalog, kind) => IsCatalogsWithTheSameKindHasDifferentId(service, catalog))
                   .When(catalog => !IsCatalogKindUnqiue(service, catalog.Kind), ApplyConditionTo.CurrentValidator)
                   .WithMessage(localizer["KindNotUnique"]);
        }

        private bool IsCatalogKindUnqiue(IRequestHandler<GetCatalogByKindRequest, CatalogDTO> service, string value)
        {
            var request = new GetCatalogByKindRequest() { Kind = value };

            return service.Execute(request) == null;
        }

        private bool IsCatalogsWithTheSameKindHasDifferentId(IRequestHandler<GetCatalogByKindRequest, CatalogDTO> service, CatalogViewModel catalog)
        {
            var request = new GetCatalogByKindRequest() { Kind = catalog.Kind };
            var catalogDTO = service.Execute(request);

            return catalogDTO.CatalogId == catalog.CatalogId;
        }
    }
}

CatalogManager/Pages/Catalogs/CatalogCreate.cshtml.cs
using System;
using System.ComponentModel.DataAnnotations;
using AutoMapper;
using BusinessLogic.DTO;
using BusinessLogic.ParametrObjects.Commands.Catalogs;
using BusinessLogic.Services.Commands;
using CatalogsManager.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CatalogsManager.Pages.Catalogs
{
    [Authorize("AllowedEditCatalogs")]
    public class CatalogCreateModel : PageModel
    {
        [Required]
        [BindProperty]
        public CatalogViewModel Catalog { get; set; }

        private readonly ICommandHandler<CreateCatalogCommand> _service;
        private readonly IMapper _mapper;

        public CatalogCreateModel(ICommandHandler<CreateCatalogCommand> service, IMapper mapper)
        {
            _service = service ??
                throw new ArgumentNullException(nameof(service));
            _mapper = mapper ??
                throw new ArgumentNullException(nameof(mapper));
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var mappedCatalog = _mapper.Map<CatalogDTO>(Catalog);
            var command = new CreateCatalogCommand() { Catalog = mappedCatalog };

            _service.Execute(command);

            return RedirectToPage("CatalogsView");
        }
    }
}

CatalogManager/Pages/Catalogs/CatalogEdit.cshtml.cs
using System;
using AutoMapper;
using BusinessLogic.DTO;
using BusinessLogic.ParametrObjects.Commands.Catalogs;
using BusinessLogic.Services.Commands;
using CatalogsManager.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CatalogsManager.Pages.Catalogs
{
    [Authorize("AllowedEditCatalogs")]
    public class CatalogEditModel : PageModel
    {
        [BindProperty(SupportsGet=true)]
        public CatalogViewModel Catalog { get; set; }

        private readonly ICommandHandler<UpdateCatalogCommand> _updateService;
        private readonly ICommandHandler<DeleteCatalogByIdCommand> _deleteService;

        private readonly IMapper _mapper;

        public CatalogEditModel(
            ICommandHandler<UpdateCatalogCommand> updateService,
            ICommandHandler<DeleteCatalogByIdCommand> deleteService,
            IMapper mapper)
        {
            _updateService = updateService ??
                throw new ArgumentNullException(nameof(updateService));
            _deleteService = deleteService ??
                throw new ArgumentNullException(nameof(deleteService));
            _mapper = mapper ??
                throw new ArgumentNullException(nameof(mapper));
        }

        public IActionResult OnPostUpdate()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var mappedCatalog = _mapper.Map<CatalogDTO>(Catalog);
            var command = new UpdateCatalogCommand() { Catalog = mappedCatalog };

            _updateService.Execute(command);

            return RedirectToPage(nameof(CatalogsView));
        }

        public IActionResult OnPostDelete()
        {
            var command = new DeleteCatalogByIdCommand() { Id = Catalog.CatalogId };

            _deleteService.Execute(command);

            return RedirectToPage(nameof(CatalogsView));
        }
    }
}

CatalogManager/Pages/Catalogs/CatalogsView.cshtml.cs
using System;
using System.Collections.Generic;
using CatalogsManager.ViewModels;
using CatalogsManager.Presentors;
using CatalogsManager.Presentors.Requests;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CatalogsManager.Pages.Catalogs
{
    public class CatalogsView : PageModel
    {
        public IEnumerable<CatalogViewModel> Catalogs { get; private set; }

        private readonly IPresentor<IEnumerable<CatalogViewModel>, GetAllCatalogs> _presentor;

        public CatalogsView(IPresentor<IEnumerable<CatalogViewModel>, GetAllCatalogs> presentor)
        {
            _presentor = presentor ??
                throw new ArgumentNullException(nameof(presentor));
        }

        public IActionResult OnGet()
        {
            var request = new GetAllCatalogs();
            Catalogs = _presentor.Get(request);

            return Page();
        }
    }
}

CatalogManager/Pages/Catalogs/CatalogCreate.cshtml
@page
@model CatalogsManager.Pages.Catalogs.CatalogCreateModel
@inject IViewLocalizer Localizer

<h1 class="cmn-h_1">@Localizer["PageDescription"]</h1>

<form method="post">
    <div class="form-group">
        <label class="cmn-lbl-description_input">@Localizer["Kind"]</label>
        <input class="form-control" asp-for="Catalog.Kind" />
        <span asp-validation-for="Catalog.Kind" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-info cmn-btn-action">@Localizer["Create"]</button>
</form>

@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
}

CatalogManager/Pages/Catalogs/CatalogEdit.cshtml
@page
@model CatalogsManager.Pages.Catalogs.CatalogEditModel
@inject IViewLocalizer Localizer

<h1 class="cmn-h_1">@Localizer["PageDescription"] @Model.Catalog.Kind</h1>

<form method="post">
    <label asp-for="@Model.Catalog.Kind" class="cmn-lbl-description_input"></label>
    <input class="form-control" asp-for="@Model.Catalog.Kind" />
    <span asp-validation-for="@Model.Catalog.Kind"></span>

    <input type="hidden" asp-for="@Model.Catalog.CatalogId" />

    <div class="cmn-item-bottom_item">
        <button type="submit" asp-page-handler="Update" class="btn btn-info">@Localizer["Edit"]</button>
        <button type="submit" asp-page-handler="Delete" class="btn btn-danger">@Localizer["Delete"]</button>
    </div>
</form>

@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
}

CatalogManager/Pages/Catalogs/CatalogsView.cshtml
@page
@model CatalogsManager.Pages.Catalogs.CatalogsView
@inject IViewLocalizer Localizer

<html>
<body>
    <h1 class="cmn-h_1">@Localizer["PageDescription"]</h1>
    <ul class="cmn-list-style">
        @foreach (var catalog in Model.Catalogs)
        {
            <li class="d-flex justify-content-between list-group-item list-group-centre">
                <div class="cmn-text-style_list-parent">
                    <p class="cmn-text-style-list-inner">@catalog.Kind</p>
                </div>

                @{
                    var routeAllCatalogData = new Dictionary<string, string>()
                    {
                        ["catalogId"] = catalog.CatalogId.ToString(),
                        ["kind"] = catalog.Kind,
                    };
                }

                <div class="group-action-buttons">
                    <a class="btn btn-info cmn-btn-action cmn-link-style-list-parent"
                       asp-page="/Groups/GroupsView" asp-all-route-data="@routeAllCatalogData">@Localizer["View"]</a>

                    @if (User.Identity.IsAuthenticated)
                    {
                        <a class="btn btn-danger ml-1 cmn-btn-action cmn-link-style-list-parent"
                           asp-page="CatalogEdit" asp-all-route-data="@routeAllCatalogData">@Localizer["Edit"]</a>
                    }
                </div>
            </li>
        }
    </ul>

    @if (User.Identity.IsAuthenticated)
    {
        <form method="get" asp-page="CatalogCreate">
            <button type="submit" class="btn btn-info cmn-item-bottom_item">@Localizer["Create"]</button>
        </form>
    }
</body>
</html>

@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
}