CatalogManager/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;

namespace CatalogsManager.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public IActionResult OnGet()
        {
            return RedirectToPage("/Catalogs/CatalogsView");
        }

        public IActionResult OnPostChangeLocalization(string culture, string returnUrl)
        {
            var requestCulture = new RequestCulture(culture);
            var cookieOptions = new CookieOptions
            {
                Expires = DateTimeOffset.Now.AddDays(30)
            };

            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(requestCulture),
                cookieOptions);

            return LocalRedirect(returnUrl);
        }
    }
}

CatalogManager/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CatalogsManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/commonPagesStyle.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 justify-content-between">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">CatalogsManager</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex">
                    <ul class="navbar-nav justify-content-end form-inline">
                        <li class="nav-link my-sm-0">
                            <partial name="_Localization" />
                        </li>

                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CatalogsManager - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CatalogManager/Pages/Shared/_Localization.cshtml
@using Microsoft.AspNetCore.Builder;
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.AspNetCore.Localization 
@using Microsoft.Extensions.Options;

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocalizationOptions

@{ 
    var culture = Context.Features.Get<IRequestCultureFeature>();
    var supportedCultures = LocalizationOptions.Value.SupportedUICultures
        .Select(cultureInfo => new SelectListItem
        {
            Value = cultureInfo.Name,
            Text = cultureInfo.Name,
        })
        .ToList();
    var returnUrl = string.IsNullOrWhiteSpace(Context.Request.Path) ? "~/" :
        $"{Context.Request.Path.Value}{Context.Request.QueryString}";
}

<div>
    <form method="post" asp-page="/Index", asp-page-handler="ChangeLocalization" asp-route-returnUrl="@returnUrl">
        <select name="culture" 
                asp-for="@culture.RequestCulture.UICulture.Name" 
                asp-items="@supportedCultures" 
                onchange="this.form.submit();">
        </select>
    </form>
</div>